# Default values for hydra-docker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port: 3002
  type: LoadBalancer

image:
  pullPolicy: Always

serviceAccount:
  create: true
  name: ksa-cloud-sql
  automount: false
  annotations: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,Content-Type,X-API-KEY"
  tls:
    - hosts:
        - api-prod-oc-gov.sidan.io
      secretName: sidangovapi-tls
  hosts:
    - host: api-prod-oc-gov.sidan.io
      paths:
        - path: /
          pathType: Prefix

env:
  secret:
    BLOCKFROST_KEY_SECRET_RESOURCE_NAME: data_from_circleci
    NEXT_PUBLIC_SIDAN_POOL_ID: data_from_circleci
    DNEXT_PUBLIC_SIDAN_DREP_ID: data_from_circleci
    NEXT_PUBLIC_SIDAN_DREP_ID_129: data_from_circleci
    DATABASE_URL: data_from_circleci
    JWT_SECRET: data_from_circleci
    PORT: data_from_circleci
    ADMIN_WALLET_ADDRESSES: data_from_circleci
  normal:

cloudsqlproxy:
  enabled: true
  name: cloud-sql-proxy
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
  args:
    - "--private-ip"
    - "--auto-iam-authn"
    - "--port=5432"
    - "sidan-445102:asia-east2:sidan-onchain-governance-prod"
  securityContext:
    runAsNonRoot: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

resources:
  requests:
    memory: "256Mi"
    cpu: "256m"
  limits:
    memory: "512Mi"
    cpu: "512m"
