apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sidan-gov-api.fullname" . }}-secret
  labels:
    {{- include "sidan-gov-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
